CREATE TABLE `OWNER` (
  ID INT NOT NULL AUTO_INCREMENT,
  NAME VARCHAR(45) NOT NULL,
  PHOTO_URL TEXT NULL,
  PRIMARY KEY (ID));

CREATE TABLE PET (
  ID INT NOT NULL AUTO_INCREMENT,
  NAME VARCHAR(45) NOT NULL,
  PHOTO_URL TEXT NULL,
  BIRTH_DAY DATE NULL,
  PRICE DECIMAL(10, 2) NULL,
  OWNER_ID INT NULL,
  PRIMARY KEY (ID),
  CONSTRAINT fk_PET_OWNER
    FOREIGN KEY (OWNER_ID)
    REFERENCES OWNER (ID)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);